// Code generated by go-swagger; DO NOT EDIT.

package workspaces_permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// NewUpdatePermissionsParams creates a new UpdatePermissionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePermissionsParams() *UpdatePermissionsParams {
	return &UpdatePermissionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePermissionsParamsWithTimeout creates a new UpdatePermissionsParams object
// with the ability to set a timeout on a request.
func NewUpdatePermissionsParamsWithTimeout(timeout time.Duration) *UpdatePermissionsParams {
	return &UpdatePermissionsParams{
		timeout: timeout,
	}
}

// NewUpdatePermissionsParamsWithContext creates a new UpdatePermissionsParams object
// with the ability to set a context for a request.
func NewUpdatePermissionsParamsWithContext(ctx context.Context) *UpdatePermissionsParams {
	return &UpdatePermissionsParams{
		Context: ctx,
	}
}

// NewUpdatePermissionsParamsWithHTTPClient creates a new UpdatePermissionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePermissionsParamsWithHTTPClient(client *http.Client) *UpdatePermissionsParams {
	return &UpdatePermissionsParams{
		HTTPClient: client,
	}
}

/*
UpdatePermissionsParams contains all the parameters to send to the API endpoint

	for the update permissions operation.

	Typically these are written to a http.Request.
*/
type UpdatePermissionsParams struct {

	/* Body.

	   The collection of permissions to update.
	*/
	Body []*models.Permission

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePermissionsParams) WithDefaults() *UpdatePermissionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update permissions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePermissionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update permissions params
func (o *UpdatePermissionsParams) WithTimeout(timeout time.Duration) *UpdatePermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update permissions params
func (o *UpdatePermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update permissions params
func (o *UpdatePermissionsParams) WithContext(ctx context.Context) *UpdatePermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update permissions params
func (o *UpdatePermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update permissions params
func (o *UpdatePermissionsParams) WithHTTPClient(client *http.Client) *UpdatePermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update permissions params
func (o *UpdatePermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update permissions params
func (o *UpdatePermissionsParams) WithBody(body []*models.Permission) *UpdatePermissionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update permissions params
func (o *UpdatePermissionsParams) SetBody(body []*models.Permission) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
