// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// NewCreateScheduleMultipleTriggersParams creates a new CreateScheduleMultipleTriggersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateScheduleMultipleTriggersParams() *CreateScheduleMultipleTriggersParams {
	return &CreateScheduleMultipleTriggersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateScheduleMultipleTriggersParamsWithTimeout creates a new CreateScheduleMultipleTriggersParams object
// with the ability to set a timeout on a request.
func NewCreateScheduleMultipleTriggersParamsWithTimeout(timeout time.Duration) *CreateScheduleMultipleTriggersParams {
	return &CreateScheduleMultipleTriggersParams{
		timeout: timeout,
	}
}

// NewCreateScheduleMultipleTriggersParamsWithContext creates a new CreateScheduleMultipleTriggersParams object
// with the ability to set a context for a request.
func NewCreateScheduleMultipleTriggersParamsWithContext(ctx context.Context) *CreateScheduleMultipleTriggersParams {
	return &CreateScheduleMultipleTriggersParams{
		Context: ctx,
	}
}

// NewCreateScheduleMultipleTriggersParamsWithHTTPClient creates a new CreateScheduleMultipleTriggersParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateScheduleMultipleTriggersParamsWithHTTPClient(client *http.Client) *CreateScheduleMultipleTriggersParams {
	return &CreateScheduleMultipleTriggersParams{
		HTTPClient: client,
	}
}

/*
CreateScheduleMultipleTriggersParams contains all the parameters to send to the API endpoint

	for the create schedule multiple triggers operation.

	Typically these are written to a http.Request.
*/
type CreateScheduleMultipleTriggersParams struct {

	/* Body.

	   Schedule with first trigger
	*/
	Body *models.CreateScheduleMultipleTriggerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create schedule multiple triggers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateScheduleMultipleTriggersParams) WithDefaults() *CreateScheduleMultipleTriggersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create schedule multiple triggers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateScheduleMultipleTriggersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) WithTimeout(timeout time.Duration) *CreateScheduleMultipleTriggersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) WithContext(ctx context.Context) *CreateScheduleMultipleTriggersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) WithHTTPClient(client *http.Client) *CreateScheduleMultipleTriggersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) WithBody(body *models.CreateScheduleMultipleTriggerRequest) *CreateScheduleMultipleTriggersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create schedule multiple triggers params
func (o *CreateScheduleMultipleTriggersParams) SetBody(body *models.CreateScheduleMultipleTriggerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateScheduleMultipleTriggersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
