// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTriggerFromScheduleMultipleParams creates a new DeleteTriggerFromScheduleMultipleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTriggerFromScheduleMultipleParams() *DeleteTriggerFromScheduleMultipleParams {
	return &DeleteTriggerFromScheduleMultipleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTriggerFromScheduleMultipleParamsWithTimeout creates a new DeleteTriggerFromScheduleMultipleParams object
// with the ability to set a timeout on a request.
func NewDeleteTriggerFromScheduleMultipleParamsWithTimeout(timeout time.Duration) *DeleteTriggerFromScheduleMultipleParams {
	return &DeleteTriggerFromScheduleMultipleParams{
		timeout: timeout,
	}
}

// NewDeleteTriggerFromScheduleMultipleParamsWithContext creates a new DeleteTriggerFromScheduleMultipleParams object
// with the ability to set a context for a request.
func NewDeleteTriggerFromScheduleMultipleParamsWithContext(ctx context.Context) *DeleteTriggerFromScheduleMultipleParams {
	return &DeleteTriggerFromScheduleMultipleParams{
		Context: ctx,
	}
}

// NewDeleteTriggerFromScheduleMultipleParamsWithHTTPClient creates a new DeleteTriggerFromScheduleMultipleParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTriggerFromScheduleMultipleParamsWithHTTPClient(client *http.Client) *DeleteTriggerFromScheduleMultipleParams {
	return &DeleteTriggerFromScheduleMultipleParams{
		HTTPClient: client,
	}
}

/*
DeleteTriggerFromScheduleMultipleParams contains all the parameters to send to the API endpoint

	for the delete trigger from schedule multiple operation.

	Typically these are written to a http.Request.
*/
type DeleteTriggerFromScheduleMultipleParams struct {

	/* Name.

	   name
	*/
	Name *string

	/* ScheduleID.

	   schedule id
	*/
	ScheduleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete trigger from schedule multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTriggerFromScheduleMultipleParams) WithDefaults() *DeleteTriggerFromScheduleMultipleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete trigger from schedule multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTriggerFromScheduleMultipleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) WithTimeout(timeout time.Duration) *DeleteTriggerFromScheduleMultipleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) WithContext(ctx context.Context) *DeleteTriggerFromScheduleMultipleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) WithHTTPClient(client *http.Client) *DeleteTriggerFromScheduleMultipleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) WithName(name *string) *DeleteTriggerFromScheduleMultipleParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) SetName(name *string) {
	o.Name = name
}

// WithScheduleID adds the scheduleID to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) WithScheduleID(scheduleID string) *DeleteTriggerFromScheduleMultipleParams {
	o.SetScheduleID(scheduleID)
	return o
}

// SetScheduleID adds the scheduleId to the delete trigger from schedule multiple params
func (o *DeleteTriggerFromScheduleMultipleParams) SetScheduleID(scheduleID string) {
	o.ScheduleID = scheduleID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTriggerFromScheduleMultipleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	// path param scheduleId
	if err := r.SetPathParam("scheduleId", o.ScheduleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
