// Code generated by go-swagger; DO NOT EDIT.

package runtime_engines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// NewDebugRemoteEngineParams creates a new DebugRemoteEngineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDebugRemoteEngineParams() *DebugRemoteEngineParams {
	return &DebugRemoteEngineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDebugRemoteEngineParamsWithTimeout creates a new DebugRemoteEngineParams object
// with the ability to set a timeout on a request.
func NewDebugRemoteEngineParamsWithTimeout(timeout time.Duration) *DebugRemoteEngineParams {
	return &DebugRemoteEngineParams{
		timeout: timeout,
	}
}

// NewDebugRemoteEngineParamsWithContext creates a new DebugRemoteEngineParams object
// with the ability to set a context for a request.
func NewDebugRemoteEngineParamsWithContext(ctx context.Context) *DebugRemoteEngineParams {
	return &DebugRemoteEngineParams{
		Context: ctx,
	}
}

// NewDebugRemoteEngineParamsWithHTTPClient creates a new DebugRemoteEngineParams object
// with the ability to set a custom HTTPClient for a request.
func NewDebugRemoteEngineParamsWithHTTPClient(client *http.Client) *DebugRemoteEngineParams {
	return &DebugRemoteEngineParams{
		HTTPClient: client,
	}
}

/*
DebugRemoteEngineParams contains all the parameters to send to the API endpoint

	for the debug remote engine operation.

	Typically these are written to a http.Request.
*/
type DebugRemoteEngineParams struct {

	/* Body.

	   Debug Remote Engine Parameters
	*/
	Body *models.DebugRemoteEngineModel

	/* RemoteEngineID.

	   Remote Engine ID
	*/
	RemoteEngineID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the debug remote engine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DebugRemoteEngineParams) WithDefaults() *DebugRemoteEngineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the debug remote engine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DebugRemoteEngineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the debug remote engine params
func (o *DebugRemoteEngineParams) WithTimeout(timeout time.Duration) *DebugRemoteEngineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the debug remote engine params
func (o *DebugRemoteEngineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the debug remote engine params
func (o *DebugRemoteEngineParams) WithContext(ctx context.Context) *DebugRemoteEngineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the debug remote engine params
func (o *DebugRemoteEngineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the debug remote engine params
func (o *DebugRemoteEngineParams) WithHTTPClient(client *http.Client) *DebugRemoteEngineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the debug remote engine params
func (o *DebugRemoteEngineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the debug remote engine params
func (o *DebugRemoteEngineParams) WithBody(body *models.DebugRemoteEngineModel) *DebugRemoteEngineParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the debug remote engine params
func (o *DebugRemoteEngineParams) SetBody(body *models.DebugRemoteEngineModel) {
	o.Body = body
}

// WithRemoteEngineID adds the remoteEngineID to the debug remote engine params
func (o *DebugRemoteEngineParams) WithRemoteEngineID(remoteEngineID string) *DebugRemoteEngineParams {
	o.SetRemoteEngineID(remoteEngineID)
	return o
}

// SetRemoteEngineID adds the remoteEngineId to the debug remote engine params
func (o *DebugRemoteEngineParams) SetRemoteEngineID(remoteEngineID string) {
	o.RemoteEngineID = remoteEngineID
}

// WriteToRequest writes these params to a swagger request
func (o *DebugRemoteEngineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param remoteEngineId
	if err := r.SetPathParam("remoteEngineId", o.RemoteEngineID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
