// Code generated by go-swagger; DO NOT EDIT.

package runtime_pipeline_engines_run_profiles_big_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// CreateRunProfileBigDataReader is a Reader for the CreateRunProfileBigData structure.
type CreateRunProfileBigDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRunProfileBigDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRunProfileBigDataCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRunProfileBigDataBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateRunProfileBigDataUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRunProfileBigDataForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateRunProfileBigDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRunProfileBigDataInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRunProfileBigDataCreated creates a CreateRunProfileBigDataCreated with default headers values
func NewCreateRunProfileBigDataCreated() *CreateRunProfileBigDataCreated {
	return &CreateRunProfileBigDataCreated{}
}

/*
CreateRunProfileBigDataCreated describes a response with status code 201, with default header values.

Created
*/
type CreateRunProfileBigDataCreated struct {
}

// IsSuccess returns true when this create run profile big data created response has a 2xx status code
func (o *CreateRunProfileBigDataCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create run profile big data created response has a 3xx status code
func (o *CreateRunProfileBigDataCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create run profile big data created response has a 4xx status code
func (o *CreateRunProfileBigDataCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create run profile big data created response has a 5xx status code
func (o *CreateRunProfileBigDataCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create run profile big data created response a status code equal to that given
func (o *CreateRunProfileBigDataCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateRunProfileBigDataCreated) Error() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataCreated ", 201)
}

func (o *CreateRunProfileBigDataCreated) String() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataCreated ", 201)
}

func (o *CreateRunProfileBigDataCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRunProfileBigDataBadRequest creates a CreateRunProfileBigDataBadRequest with default headers values
func NewCreateRunProfileBigDataBadRequest() *CreateRunProfileBigDataBadRequest {
	return &CreateRunProfileBigDataBadRequest{}
}

/*
CreateRunProfileBigDataBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateRunProfileBigDataBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create run profile big data bad request response has a 2xx status code
func (o *CreateRunProfileBigDataBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create run profile big data bad request response has a 3xx status code
func (o *CreateRunProfileBigDataBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create run profile big data bad request response has a 4xx status code
func (o *CreateRunProfileBigDataBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create run profile big data bad request response has a 5xx status code
func (o *CreateRunProfileBigDataBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create run profile big data bad request response a status code equal to that given
func (o *CreateRunProfileBigDataBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateRunProfileBigDataBadRequest) Error() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataBadRequest  %+v", 400, o.Payload)
}

func (o *CreateRunProfileBigDataBadRequest) String() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataBadRequest  %+v", 400, o.Payload)
}

func (o *CreateRunProfileBigDataBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateRunProfileBigDataBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRunProfileBigDataUnauthorized creates a CreateRunProfileBigDataUnauthorized with default headers values
func NewCreateRunProfileBigDataUnauthorized() *CreateRunProfileBigDataUnauthorized {
	return &CreateRunProfileBigDataUnauthorized{}
}

/*
CreateRunProfileBigDataUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateRunProfileBigDataUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create run profile big data unauthorized response has a 2xx status code
func (o *CreateRunProfileBigDataUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create run profile big data unauthorized response has a 3xx status code
func (o *CreateRunProfileBigDataUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create run profile big data unauthorized response has a 4xx status code
func (o *CreateRunProfileBigDataUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create run profile big data unauthorized response has a 5xx status code
func (o *CreateRunProfileBigDataUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create run profile big data unauthorized response a status code equal to that given
func (o *CreateRunProfileBigDataUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateRunProfileBigDataUnauthorized) Error() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateRunProfileBigDataUnauthorized) String() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateRunProfileBigDataUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateRunProfileBigDataUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRunProfileBigDataForbidden creates a CreateRunProfileBigDataForbidden with default headers values
func NewCreateRunProfileBigDataForbidden() *CreateRunProfileBigDataForbidden {
	return &CreateRunProfileBigDataForbidden{}
}

/*
CreateRunProfileBigDataForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateRunProfileBigDataForbidden struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create run profile big data forbidden response has a 2xx status code
func (o *CreateRunProfileBigDataForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create run profile big data forbidden response has a 3xx status code
func (o *CreateRunProfileBigDataForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create run profile big data forbidden response has a 4xx status code
func (o *CreateRunProfileBigDataForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create run profile big data forbidden response has a 5xx status code
func (o *CreateRunProfileBigDataForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create run profile big data forbidden response a status code equal to that given
func (o *CreateRunProfileBigDataForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateRunProfileBigDataForbidden) Error() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataForbidden  %+v", 403, o.Payload)
}

func (o *CreateRunProfileBigDataForbidden) String() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataForbidden  %+v", 403, o.Payload)
}

func (o *CreateRunProfileBigDataForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateRunProfileBigDataForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRunProfileBigDataNotFound creates a CreateRunProfileBigDataNotFound with default headers values
func NewCreateRunProfileBigDataNotFound() *CreateRunProfileBigDataNotFound {
	return &CreateRunProfileBigDataNotFound{}
}

/*
CreateRunProfileBigDataNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateRunProfileBigDataNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create run profile big data not found response has a 2xx status code
func (o *CreateRunProfileBigDataNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create run profile big data not found response has a 3xx status code
func (o *CreateRunProfileBigDataNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create run profile big data not found response has a 4xx status code
func (o *CreateRunProfileBigDataNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create run profile big data not found response has a 5xx status code
func (o *CreateRunProfileBigDataNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create run profile big data not found response a status code equal to that given
func (o *CreateRunProfileBigDataNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateRunProfileBigDataNotFound) Error() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataNotFound  %+v", 404, o.Payload)
}

func (o *CreateRunProfileBigDataNotFound) String() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataNotFound  %+v", 404, o.Payload)
}

func (o *CreateRunProfileBigDataNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateRunProfileBigDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRunProfileBigDataInternalServerError creates a CreateRunProfileBigDataInternalServerError with default headers values
func NewCreateRunProfileBigDataInternalServerError() *CreateRunProfileBigDataInternalServerError {
	return &CreateRunProfileBigDataInternalServerError{}
}

/*
CreateRunProfileBigDataInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateRunProfileBigDataInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create run profile big data internal server error response has a 2xx status code
func (o *CreateRunProfileBigDataInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create run profile big data internal server error response has a 3xx status code
func (o *CreateRunProfileBigDataInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create run profile big data internal server error response has a 4xx status code
func (o *CreateRunProfileBigDataInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create run profile big data internal server error response has a 5xx status code
func (o *CreateRunProfileBigDataInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create run profile big data internal server error response a status code equal to that given
func (o *CreateRunProfileBigDataInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CreateRunProfileBigDataInternalServerError) Error() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateRunProfileBigDataInternalServerError) String() string {
	return fmt.Sprintf("[POST /runtimes/pipeline-engines/{engineId}/run-profiles/big-data][%d] createRunProfileBigDataInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateRunProfileBigDataInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateRunProfileBigDataInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
