// Code generated by go-swagger; DO NOT EDIT.

package plans_executions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllStepExecutionsParams creates a new GetAllStepExecutionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllStepExecutionsParams() *GetAllStepExecutionsParams {
	return &GetAllStepExecutionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllStepExecutionsParamsWithTimeout creates a new GetAllStepExecutionsParams object
// with the ability to set a timeout on a request.
func NewGetAllStepExecutionsParamsWithTimeout(timeout time.Duration) *GetAllStepExecutionsParams {
	return &GetAllStepExecutionsParams{
		timeout: timeout,
	}
}

// NewGetAllStepExecutionsParamsWithContext creates a new GetAllStepExecutionsParams object
// with the ability to set a context for a request.
func NewGetAllStepExecutionsParamsWithContext(ctx context.Context) *GetAllStepExecutionsParams {
	return &GetAllStepExecutionsParams{
		Context: ctx,
	}
}

// NewGetAllStepExecutionsParamsWithHTTPClient creates a new GetAllStepExecutionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllStepExecutionsParamsWithHTTPClient(client *http.Client) *GetAllStepExecutionsParams {
	return &GetAllStepExecutionsParams{
		HTTPClient: client,
	}
}

/*
GetAllStepExecutionsParams contains all the parameters to send to the API endpoint

	for the get all step executions operation.

	Typically these are written to a http.Request.
*/
type GetAllStepExecutionsParams struct {

	/* PlanExecutionID.

	   Plan execution ID
	*/
	PlanExecutionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all step executions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllStepExecutionsParams) WithDefaults() *GetAllStepExecutionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all step executions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllStepExecutionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all step executions params
func (o *GetAllStepExecutionsParams) WithTimeout(timeout time.Duration) *GetAllStepExecutionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all step executions params
func (o *GetAllStepExecutionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all step executions params
func (o *GetAllStepExecutionsParams) WithContext(ctx context.Context) *GetAllStepExecutionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all step executions params
func (o *GetAllStepExecutionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all step executions params
func (o *GetAllStepExecutionsParams) WithHTTPClient(client *http.Client) *GetAllStepExecutionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all step executions params
func (o *GetAllStepExecutionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPlanExecutionID adds the planExecutionID to the get all step executions params
func (o *GetAllStepExecutionsParams) WithPlanExecutionID(planExecutionID string) *GetAllStepExecutionsParams {
	o.SetPlanExecutionID(planExecutionID)
	return o
}

// SetPlanExecutionID adds the planExecutionId to the get all step executions params
func (o *GetAllStepExecutionsParams) SetPlanExecutionID(planExecutionID string) {
	o.PlanExecutionID = planExecutionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllStepExecutionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param planExecutionId
	if err := r.SetPathParam("planExecutionId", o.PlanExecutionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
