// Code generated by go-swagger; DO NOT EDIT.

package runtime_pipeline_engines_run_profiles_databricks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new runtime pipeline engines run profiles databricks API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for runtime pipeline engines run profiles databricks API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateRunProfileDatabricks(params *CreateRunProfileDatabricksParams, opts ...ClientOption) (*CreateRunProfileDatabricksCreated, error)

	GetDatabricksRunProfileByID(params *GetDatabricksRunProfileByIDParams, opts ...ClientOption) (*GetDatabricksRunProfileByIDOK, error)

	UpdateRunProfileDatabricks(params *UpdateRunProfileDatabricksParams, opts ...ClientOption) (*UpdateRunProfileDatabricksNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateRunProfileDatabricks creates new run profile
*/
func (a *Client) CreateRunProfileDatabricks(params *CreateRunProfileDatabricksParams, opts ...ClientOption) (*CreateRunProfileDatabricksCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateRunProfileDatabricksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createRunProfileDatabricks",
		Method:             "POST",
		PathPattern:        "/runtimes/pipeline-engines/{engineId}/run-profiles/databricks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateRunProfileDatabricksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateRunProfileDatabricksCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createRunProfileDatabricks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetDatabricksRunProfileByID gets run profile
*/
func (a *Client) GetDatabricksRunProfileByID(params *GetDatabricksRunProfileByIDParams, opts ...ClientOption) (*GetDatabricksRunProfileByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDatabricksRunProfileByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getDatabricksRunProfileById",
		Method:             "GET",
		PathPattern:        "/runtimes/pipeline-engines/{engineId}/run-profiles/databricks/{runProfileId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDatabricksRunProfileByIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDatabricksRunProfileByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDatabricksRunProfileById: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateRunProfileDatabricks updates run profile
*/
func (a *Client) UpdateRunProfileDatabricks(params *UpdateRunProfileDatabricksParams, opts ...ClientOption) (*UpdateRunProfileDatabricksNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateRunProfileDatabricksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateRunProfileDatabricks",
		Method:             "PUT",
		PathPattern:        "/runtimes/pipeline-engines/{engineId}/run-profiles/databricks/{runProfileId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateRunProfileDatabricksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateRunProfileDatabricksNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateRunProfileDatabricks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
