// Code generated by go-swagger; DO NOT EDIT.

package runtime_engines_run_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// NewUpdateEngineRunProfileParams creates a new UpdateEngineRunProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateEngineRunProfileParams() *UpdateEngineRunProfileParams {
	return &UpdateEngineRunProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEngineRunProfileParamsWithTimeout creates a new UpdateEngineRunProfileParams object
// with the ability to set a timeout on a request.
func NewUpdateEngineRunProfileParamsWithTimeout(timeout time.Duration) *UpdateEngineRunProfileParams {
	return &UpdateEngineRunProfileParams{
		timeout: timeout,
	}
}

// NewUpdateEngineRunProfileParamsWithContext creates a new UpdateEngineRunProfileParams object
// with the ability to set a context for a request.
func NewUpdateEngineRunProfileParamsWithContext(ctx context.Context) *UpdateEngineRunProfileParams {
	return &UpdateEngineRunProfileParams{
		Context: ctx,
	}
}

// NewUpdateEngineRunProfileParamsWithHTTPClient creates a new UpdateEngineRunProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateEngineRunProfileParamsWithHTTPClient(client *http.Client) *UpdateEngineRunProfileParams {
	return &UpdateEngineRunProfileParams{
		HTTPClient: client,
	}
}

/*
UpdateEngineRunProfileParams contains all the parameters to send to the API endpoint

	for the update engine run profile operation.

	Typically these are written to a http.Request.
*/
type UpdateEngineRunProfileParams struct {

	/* Body.

	   update run profile
	*/
	Body *models.RunProfileUpdateRequest

	/* EngineID.

	   remote engine id
	*/
	EngineID string

	/* RunProfileID.

	   run profile id
	*/
	RunProfileID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update engine run profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEngineRunProfileParams) WithDefaults() *UpdateEngineRunProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update engine run profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEngineRunProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update engine run profile params
func (o *UpdateEngineRunProfileParams) WithTimeout(timeout time.Duration) *UpdateEngineRunProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update engine run profile params
func (o *UpdateEngineRunProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update engine run profile params
func (o *UpdateEngineRunProfileParams) WithContext(ctx context.Context) *UpdateEngineRunProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update engine run profile params
func (o *UpdateEngineRunProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update engine run profile params
func (o *UpdateEngineRunProfileParams) WithHTTPClient(client *http.Client) *UpdateEngineRunProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update engine run profile params
func (o *UpdateEngineRunProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update engine run profile params
func (o *UpdateEngineRunProfileParams) WithBody(body *models.RunProfileUpdateRequest) *UpdateEngineRunProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update engine run profile params
func (o *UpdateEngineRunProfileParams) SetBody(body *models.RunProfileUpdateRequest) {
	o.Body = body
}

// WithEngineID adds the engineID to the update engine run profile params
func (o *UpdateEngineRunProfileParams) WithEngineID(engineID string) *UpdateEngineRunProfileParams {
	o.SetEngineID(engineID)
	return o
}

// SetEngineID adds the engineId to the update engine run profile params
func (o *UpdateEngineRunProfileParams) SetEngineID(engineID string) {
	o.EngineID = engineID
}

// WithRunProfileID adds the runProfileID to the update engine run profile params
func (o *UpdateEngineRunProfileParams) WithRunProfileID(runProfileID string) *UpdateEngineRunProfileParams {
	o.SetRunProfileID(runProfileID)
	return o
}

// SetRunProfileID adds the runProfileId to the update engine run profile params
func (o *UpdateEngineRunProfileParams) SetRunProfileID(runProfileID string) {
	o.RunProfileID = runProfileID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEngineRunProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param engineId
	if err := r.SetPathParam("engineId", o.EngineID); err != nil {
		return err
	}

	// path param runProfileId
	if err := r.SetPathParam("runProfileId", o.RunProfileID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
