// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// NewSearchTasksParams creates a new SearchTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchTasksParams() *SearchTasksParams {
	return &SearchTasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchTasksParamsWithTimeout creates a new SearchTasksParams object
// with the ability to set a timeout on a request.
func NewSearchTasksParamsWithTimeout(timeout time.Duration) *SearchTasksParams {
	return &SearchTasksParams{
		timeout: timeout,
	}
}

// NewSearchTasksParamsWithContext creates a new SearchTasksParams object
// with the ability to set a context for a request.
func NewSearchTasksParamsWithContext(ctx context.Context) *SearchTasksParams {
	return &SearchTasksParams{
		Context: ctx,
	}
}

// NewSearchTasksParamsWithHTTPClient creates a new SearchTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchTasksParamsWithHTTPClient(client *http.Client) *SearchTasksParams {
	return &SearchTasksParams{
		HTTPClient: client,
	}
}

/*
SearchTasksParams contains all the parameters to send to the API endpoint

	for the search tasks operation.

	Typically these are written to a http.Request.
*/
type SearchTasksParams struct {

	/* Body.

	   Search tasks filters
	*/
	Body *models.FetchTasksModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTasksParams) WithDefaults() *SearchTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search tasks params
func (o *SearchTasksParams) WithTimeout(timeout time.Duration) *SearchTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search tasks params
func (o *SearchTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search tasks params
func (o *SearchTasksParams) WithContext(ctx context.Context) *SearchTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search tasks params
func (o *SearchTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search tasks params
func (o *SearchTasksParams) WithHTTPClient(client *http.Client) *SearchTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search tasks params
func (o *SearchTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search tasks params
func (o *SearchTasksParams) WithBody(body *models.FetchTasksModel) *SearchTasksParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search tasks params
func (o *SearchTasksParams) SetBody(body *models.FetchTasksModel) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
