// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnlinkTaskScheduleParams creates a new UnlinkTaskScheduleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnlinkTaskScheduleParams() *UnlinkTaskScheduleParams {
	return &UnlinkTaskScheduleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnlinkTaskScheduleParamsWithTimeout creates a new UnlinkTaskScheduleParams object
// with the ability to set a timeout on a request.
func NewUnlinkTaskScheduleParamsWithTimeout(timeout time.Duration) *UnlinkTaskScheduleParams {
	return &UnlinkTaskScheduleParams{
		timeout: timeout,
	}
}

// NewUnlinkTaskScheduleParamsWithContext creates a new UnlinkTaskScheduleParams object
// with the ability to set a context for a request.
func NewUnlinkTaskScheduleParamsWithContext(ctx context.Context) *UnlinkTaskScheduleParams {
	return &UnlinkTaskScheduleParams{
		Context: ctx,
	}
}

// NewUnlinkTaskScheduleParamsWithHTTPClient creates a new UnlinkTaskScheduleParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnlinkTaskScheduleParamsWithHTTPClient(client *http.Client) *UnlinkTaskScheduleParams {
	return &UnlinkTaskScheduleParams{
		HTTPClient: client,
	}
}

/*
UnlinkTaskScheduleParams contains all the parameters to send to the API endpoint

	for the unlink task schedule operation.

	Typically these are written to a http.Request.
*/
type UnlinkTaskScheduleParams struct {

	/* TaskID.

	   task id
	*/
	TaskID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the unlink task schedule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnlinkTaskScheduleParams) WithDefaults() *UnlinkTaskScheduleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the unlink task schedule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnlinkTaskScheduleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) WithTimeout(timeout time.Duration) *UnlinkTaskScheduleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) WithContext(ctx context.Context) *UnlinkTaskScheduleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) WithHTTPClient(client *http.Client) *UnlinkTaskScheduleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskID adds the taskID to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) WithTaskID(taskID string) *UnlinkTaskScheduleParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the unlink task schedule params
func (o *UnlinkTaskScheduleParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *UnlinkTaskScheduleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskId
	if err := r.SetPathParam("taskId", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
