// Code generated by go-swagger; DO NOT EDIT.

package runtime_pipeline_engines_run_profiles_advanced

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAdvancedRunProfileByIDParams creates a new GetAdvancedRunProfileByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAdvancedRunProfileByIDParams() *GetAdvancedRunProfileByIDParams {
	return &GetAdvancedRunProfileByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdvancedRunProfileByIDParamsWithTimeout creates a new GetAdvancedRunProfileByIDParams object
// with the ability to set a timeout on a request.
func NewGetAdvancedRunProfileByIDParamsWithTimeout(timeout time.Duration) *GetAdvancedRunProfileByIDParams {
	return &GetAdvancedRunProfileByIDParams{
		timeout: timeout,
	}
}

// NewGetAdvancedRunProfileByIDParamsWithContext creates a new GetAdvancedRunProfileByIDParams object
// with the ability to set a context for a request.
func NewGetAdvancedRunProfileByIDParamsWithContext(ctx context.Context) *GetAdvancedRunProfileByIDParams {
	return &GetAdvancedRunProfileByIDParams{
		Context: ctx,
	}
}

// NewGetAdvancedRunProfileByIDParamsWithHTTPClient creates a new GetAdvancedRunProfileByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAdvancedRunProfileByIDParamsWithHTTPClient(client *http.Client) *GetAdvancedRunProfileByIDParams {
	return &GetAdvancedRunProfileByIDParams{
		HTTPClient: client,
	}
}

/*
GetAdvancedRunProfileByIDParams contains all the parameters to send to the API endpoint

	for the get advanced run profile by Id operation.

	Typically these are written to a http.Request.
*/
type GetAdvancedRunProfileByIDParams struct {

	/* EngineID.

	   engine id
	*/
	EngineID string

	/* RunProfileID.

	   run profile id
	*/
	RunProfileID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get advanced run profile by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdvancedRunProfileByIDParams) WithDefaults() *GetAdvancedRunProfileByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get advanced run profile by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdvancedRunProfileByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) WithTimeout(timeout time.Duration) *GetAdvancedRunProfileByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) WithContext(ctx context.Context) *GetAdvancedRunProfileByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) WithHTTPClient(client *http.Client) *GetAdvancedRunProfileByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEngineID adds the engineID to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) WithEngineID(engineID string) *GetAdvancedRunProfileByIDParams {
	o.SetEngineID(engineID)
	return o
}

// SetEngineID adds the engineId to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) SetEngineID(engineID string) {
	o.EngineID = engineID
}

// WithRunProfileID adds the runProfileID to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) WithRunProfileID(runProfileID string) *GetAdvancedRunProfileByIDParams {
	o.SetRunProfileID(runProfileID)
	return o
}

// SetRunProfileID adds the runProfileId to the get advanced run profile by Id params
func (o *GetAdvancedRunProfileByIDParams) SetRunProfileID(runProfileID string) {
	o.RunProfileID = runProfileID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdvancedRunProfileByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param engineId
	if err := r.SetPathParam("engineId", o.EngineID); err != nil {
		return err
	}

	// path param runProfileId
	if err := r.SetPathParam("runProfileId", o.RunProfileID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
