// Code generated by go-swagger; DO NOT EDIT.

package runtime_pipeline_engines_run_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePipelineRunProfileParams creates a new DeletePipelineRunProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePipelineRunProfileParams() *DeletePipelineRunProfileParams {
	return &DeletePipelineRunProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePipelineRunProfileParamsWithTimeout creates a new DeletePipelineRunProfileParams object
// with the ability to set a timeout on a request.
func NewDeletePipelineRunProfileParamsWithTimeout(timeout time.Duration) *DeletePipelineRunProfileParams {
	return &DeletePipelineRunProfileParams{
		timeout: timeout,
	}
}

// NewDeletePipelineRunProfileParamsWithContext creates a new DeletePipelineRunProfileParams object
// with the ability to set a context for a request.
func NewDeletePipelineRunProfileParamsWithContext(ctx context.Context) *DeletePipelineRunProfileParams {
	return &DeletePipelineRunProfileParams{
		Context: ctx,
	}
}

// NewDeletePipelineRunProfileParamsWithHTTPClient creates a new DeletePipelineRunProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePipelineRunProfileParamsWithHTTPClient(client *http.Client) *DeletePipelineRunProfileParams {
	return &DeletePipelineRunProfileParams{
		HTTPClient: client,
	}
}

/*
DeletePipelineRunProfileParams contains all the parameters to send to the API endpoint

	for the delete pipeline run profile operation.

	Typically these are written to a http.Request.
*/
type DeletePipelineRunProfileParams struct {

	/* EngineID.

	   engine id
	*/
	EngineID string

	/* NewRunProfileID.

	   run profile for replacement id
	*/
	NewRunProfileID *string

	/* RunProfileID.

	   run profile id
	*/
	RunProfileID string

	/* Type.

	   run profile type
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete pipeline run profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePipelineRunProfileParams) WithDefaults() *DeletePipelineRunProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete pipeline run profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePipelineRunProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithTimeout(timeout time.Duration) *DeletePipelineRunProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithContext(ctx context.Context) *DeletePipelineRunProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithHTTPClient(client *http.Client) *DeletePipelineRunProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEngineID adds the engineID to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithEngineID(engineID string) *DeletePipelineRunProfileParams {
	o.SetEngineID(engineID)
	return o
}

// SetEngineID adds the engineId to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetEngineID(engineID string) {
	o.EngineID = engineID
}

// WithNewRunProfileID adds the newRunProfileID to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithNewRunProfileID(newRunProfileID *string) *DeletePipelineRunProfileParams {
	o.SetNewRunProfileID(newRunProfileID)
	return o
}

// SetNewRunProfileID adds the newRunProfileId to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetNewRunProfileID(newRunProfileID *string) {
	o.NewRunProfileID = newRunProfileID
}

// WithRunProfileID adds the runProfileID to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithRunProfileID(runProfileID string) *DeletePipelineRunProfileParams {
	o.SetRunProfileID(runProfileID)
	return o
}

// SetRunProfileID adds the runProfileId to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetRunProfileID(runProfileID string) {
	o.RunProfileID = runProfileID
}

// WithType adds the typeVar to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) WithType(typeVar string) *DeletePipelineRunProfileParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the delete pipeline run profile params
func (o *DeletePipelineRunProfileParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePipelineRunProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param engineId
	if err := r.SetPathParam("engineId", o.EngineID); err != nil {
		return err
	}

	if o.NewRunProfileID != nil {

		// query param newRunProfileId
		var qrNewRunProfileID string

		if o.NewRunProfileID != nil {
			qrNewRunProfileID = *o.NewRunProfileID
		}
		qNewRunProfileID := qrNewRunProfileID
		if qNewRunProfileID != "" {

			if err := r.SetQueryParam("newRunProfileId", qNewRunProfileID); err != nil {
				return err
			}
		}
	}

	// path param runProfileId
	if err := r.SetPathParam("runProfileId", o.RunProfileID); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
