// Code generated by go-swagger; DO NOT EDIT.

package promotions_executions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// ExecutePromotionReader is a Reader for the ExecutePromotion structure.
type ExecutePromotionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecutePromotionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewExecutePromotionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewExecutePromotionAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExecutePromotionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExecutePromotionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewExecutePromotionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExecutePromotionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExecutePromotionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewExecutePromotionNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExecutePromotionCreated creates a ExecutePromotionCreated with default headers values
func NewExecutePromotionCreated() *ExecutePromotionCreated {
	return &ExecutePromotionCreated{}
}

/*
ExecutePromotionCreated describes a response with status code 201, with default header values.

Execution success
*/
type ExecutePromotionCreated struct {
	Payload *models.Executionidentifier
}

// IsSuccess returns true when this execute promotion created response has a 2xx status code
func (o *ExecutePromotionCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this execute promotion created response has a 3xx status code
func (o *ExecutePromotionCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion created response has a 4xx status code
func (o *ExecutePromotionCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this execute promotion created response has a 5xx status code
func (o *ExecutePromotionCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this execute promotion created response a status code equal to that given
func (o *ExecutePromotionCreated) IsCode(code int) bool {
	return code == 201
}

func (o *ExecutePromotionCreated) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionCreated  %+v", 201, o.Payload)
}

func (o *ExecutePromotionCreated) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionCreated  %+v", 201, o.Payload)
}

func (o *ExecutePromotionCreated) GetPayload() *models.Executionidentifier {
	return o.Payload
}

func (o *ExecutePromotionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Executionidentifier)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecutePromotionAccepted creates a ExecutePromotionAccepted with default headers values
func NewExecutePromotionAccepted() *ExecutePromotionAccepted {
	return &ExecutePromotionAccepted{}
}

/*
ExecutePromotionAccepted describes a response with status code 202, with default header values.

Execution started
*/
type ExecutePromotionAccepted struct {
}

// IsSuccess returns true when this execute promotion accepted response has a 2xx status code
func (o *ExecutePromotionAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this execute promotion accepted response has a 3xx status code
func (o *ExecutePromotionAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion accepted response has a 4xx status code
func (o *ExecutePromotionAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this execute promotion accepted response has a 5xx status code
func (o *ExecutePromotionAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this execute promotion accepted response a status code equal to that given
func (o *ExecutePromotionAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *ExecutePromotionAccepted) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionAccepted ", 202)
}

func (o *ExecutePromotionAccepted) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionAccepted ", 202)
}

func (o *ExecutePromotionAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExecutePromotionBadRequest creates a ExecutePromotionBadRequest with default headers values
func NewExecutePromotionBadRequest() *ExecutePromotionBadRequest {
	return &ExecutePromotionBadRequest{}
}

/*
ExecutePromotionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExecutePromotionBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this execute promotion bad request response has a 2xx status code
func (o *ExecutePromotionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this execute promotion bad request response has a 3xx status code
func (o *ExecutePromotionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion bad request response has a 4xx status code
func (o *ExecutePromotionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this execute promotion bad request response has a 5xx status code
func (o *ExecutePromotionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this execute promotion bad request response a status code equal to that given
func (o *ExecutePromotionBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ExecutePromotionBadRequest) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionBadRequest  %+v", 400, o.Payload)
}

func (o *ExecutePromotionBadRequest) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionBadRequest  %+v", 400, o.Payload)
}

func (o *ExecutePromotionBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExecutePromotionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecutePromotionUnauthorized creates a ExecutePromotionUnauthorized with default headers values
func NewExecutePromotionUnauthorized() *ExecutePromotionUnauthorized {
	return &ExecutePromotionUnauthorized{}
}

/*
ExecutePromotionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ExecutePromotionUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this execute promotion unauthorized response has a 2xx status code
func (o *ExecutePromotionUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this execute promotion unauthorized response has a 3xx status code
func (o *ExecutePromotionUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion unauthorized response has a 4xx status code
func (o *ExecutePromotionUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this execute promotion unauthorized response has a 5xx status code
func (o *ExecutePromotionUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this execute promotion unauthorized response a status code equal to that given
func (o *ExecutePromotionUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *ExecutePromotionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionUnauthorized  %+v", 401, o.Payload)
}

func (o *ExecutePromotionUnauthorized) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionUnauthorized  %+v", 401, o.Payload)
}

func (o *ExecutePromotionUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExecutePromotionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecutePromotionForbidden creates a ExecutePromotionForbidden with default headers values
func NewExecutePromotionForbidden() *ExecutePromotionForbidden {
	return &ExecutePromotionForbidden{}
}

/*
ExecutePromotionForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ExecutePromotionForbidden struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this execute promotion forbidden response has a 2xx status code
func (o *ExecutePromotionForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this execute promotion forbidden response has a 3xx status code
func (o *ExecutePromotionForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion forbidden response has a 4xx status code
func (o *ExecutePromotionForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this execute promotion forbidden response has a 5xx status code
func (o *ExecutePromotionForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this execute promotion forbidden response a status code equal to that given
func (o *ExecutePromotionForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *ExecutePromotionForbidden) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionForbidden  %+v", 403, o.Payload)
}

func (o *ExecutePromotionForbidden) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionForbidden  %+v", 403, o.Payload)
}

func (o *ExecutePromotionForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExecutePromotionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecutePromotionNotFound creates a ExecutePromotionNotFound with default headers values
func NewExecutePromotionNotFound() *ExecutePromotionNotFound {
	return &ExecutePromotionNotFound{}
}

/*
ExecutePromotionNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ExecutePromotionNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this execute promotion not found response has a 2xx status code
func (o *ExecutePromotionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this execute promotion not found response has a 3xx status code
func (o *ExecutePromotionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion not found response has a 4xx status code
func (o *ExecutePromotionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this execute promotion not found response has a 5xx status code
func (o *ExecutePromotionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this execute promotion not found response a status code equal to that given
func (o *ExecutePromotionNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ExecutePromotionNotFound) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionNotFound  %+v", 404, o.Payload)
}

func (o *ExecutePromotionNotFound) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionNotFound  %+v", 404, o.Payload)
}

func (o *ExecutePromotionNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExecutePromotionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecutePromotionInternalServerError creates a ExecutePromotionInternalServerError with default headers values
func NewExecutePromotionInternalServerError() *ExecutePromotionInternalServerError {
	return &ExecutePromotionInternalServerError{}
}

/*
ExecutePromotionInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ExecutePromotionInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this execute promotion internal server error response has a 2xx status code
func (o *ExecutePromotionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this execute promotion internal server error response has a 3xx status code
func (o *ExecutePromotionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion internal server error response has a 4xx status code
func (o *ExecutePromotionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this execute promotion internal server error response has a 5xx status code
func (o *ExecutePromotionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this execute promotion internal server error response a status code equal to that given
func (o *ExecutePromotionInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *ExecutePromotionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionInternalServerError  %+v", 500, o.Payload)
}

func (o *ExecutePromotionInternalServerError) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionInternalServerError  %+v", 500, o.Payload)
}

func (o *ExecutePromotionInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExecutePromotionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecutePromotionNotImplemented creates a ExecutePromotionNotImplemented with default headers values
func NewExecutePromotionNotImplemented() *ExecutePromotionNotImplemented {
	return &ExecutePromotionNotImplemented{}
}

/*
ExecutePromotionNotImplemented describes a response with status code 501, with default header values.

Promotions can't be executed because it has errors
*/
type ExecutePromotionNotImplemented struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this execute promotion not implemented response has a 2xx status code
func (o *ExecutePromotionNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this execute promotion not implemented response has a 3xx status code
func (o *ExecutePromotionNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this execute promotion not implemented response has a 4xx status code
func (o *ExecutePromotionNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this execute promotion not implemented response has a 5xx status code
func (o *ExecutePromotionNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this execute promotion not implemented response a status code equal to that given
func (o *ExecutePromotionNotImplemented) IsCode(code int) bool {
	return code == 501
}

func (o *ExecutePromotionNotImplemented) Error() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionNotImplemented  %+v", 501, o.Payload)
}

func (o *ExecutePromotionNotImplemented) String() string {
	return fmt.Sprintf("[POST /executions/promotions][%d] executePromotionNotImplemented  %+v", 501, o.Payload)
}

func (o *ExecutePromotionNotImplemented) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExecutePromotionNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
