// Code generated by go-swagger; DO NOT EDIT.

package promotions_executions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// PerformPromotionAnalysisReader is a Reader for the PerformPromotionAnalysis structure.
type PerformPromotionAnalysisReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PerformPromotionAnalysisReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPerformPromotionAnalysisOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPerformPromotionAnalysisBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPerformPromotionAnalysisUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPerformPromotionAnalysisForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPerformPromotionAnalysisNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPerformPromotionAnalysisInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPerformPromotionAnalysisOK creates a PerformPromotionAnalysisOK with default headers values
func NewPerformPromotionAnalysisOK() *PerformPromotionAnalysisOK {
	return &PerformPromotionAnalysisOK{}
}

/*
PerformPromotionAnalysisOK describes a response with status code 200, with default header values.

OK
*/
type PerformPromotionAnalysisOK struct {
	Payload *models.PromotionExecutionStatus
}

// IsSuccess returns true when this perform promotion analysis o k response has a 2xx status code
func (o *PerformPromotionAnalysisOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this perform promotion analysis o k response has a 3xx status code
func (o *PerformPromotionAnalysisOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this perform promotion analysis o k response has a 4xx status code
func (o *PerformPromotionAnalysisOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this perform promotion analysis o k response has a 5xx status code
func (o *PerformPromotionAnalysisOK) IsServerError() bool {
	return false
}

// IsCode returns true when this perform promotion analysis o k response a status code equal to that given
func (o *PerformPromotionAnalysisOK) IsCode(code int) bool {
	return code == 200
}

func (o *PerformPromotionAnalysisOK) Error() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisOK  %+v", 200, o.Payload)
}

func (o *PerformPromotionAnalysisOK) String() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisOK  %+v", 200, o.Payload)
}

func (o *PerformPromotionAnalysisOK) GetPayload() *models.PromotionExecutionStatus {
	return o.Payload
}

func (o *PerformPromotionAnalysisOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PromotionExecutionStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPerformPromotionAnalysisBadRequest creates a PerformPromotionAnalysisBadRequest with default headers values
func NewPerformPromotionAnalysisBadRequest() *PerformPromotionAnalysisBadRequest {
	return &PerformPromotionAnalysisBadRequest{}
}

/*
PerformPromotionAnalysisBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PerformPromotionAnalysisBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this perform promotion analysis bad request response has a 2xx status code
func (o *PerformPromotionAnalysisBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this perform promotion analysis bad request response has a 3xx status code
func (o *PerformPromotionAnalysisBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this perform promotion analysis bad request response has a 4xx status code
func (o *PerformPromotionAnalysisBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this perform promotion analysis bad request response has a 5xx status code
func (o *PerformPromotionAnalysisBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this perform promotion analysis bad request response a status code equal to that given
func (o *PerformPromotionAnalysisBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *PerformPromotionAnalysisBadRequest) Error() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisBadRequest  %+v", 400, o.Payload)
}

func (o *PerformPromotionAnalysisBadRequest) String() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisBadRequest  %+v", 400, o.Payload)
}

func (o *PerformPromotionAnalysisBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PerformPromotionAnalysisBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPerformPromotionAnalysisUnauthorized creates a PerformPromotionAnalysisUnauthorized with default headers values
func NewPerformPromotionAnalysisUnauthorized() *PerformPromotionAnalysisUnauthorized {
	return &PerformPromotionAnalysisUnauthorized{}
}

/*
PerformPromotionAnalysisUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PerformPromotionAnalysisUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this perform promotion analysis unauthorized response has a 2xx status code
func (o *PerformPromotionAnalysisUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this perform promotion analysis unauthorized response has a 3xx status code
func (o *PerformPromotionAnalysisUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this perform promotion analysis unauthorized response has a 4xx status code
func (o *PerformPromotionAnalysisUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this perform promotion analysis unauthorized response has a 5xx status code
func (o *PerformPromotionAnalysisUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this perform promotion analysis unauthorized response a status code equal to that given
func (o *PerformPromotionAnalysisUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *PerformPromotionAnalysisUnauthorized) Error() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisUnauthorized  %+v", 401, o.Payload)
}

func (o *PerformPromotionAnalysisUnauthorized) String() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisUnauthorized  %+v", 401, o.Payload)
}

func (o *PerformPromotionAnalysisUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PerformPromotionAnalysisUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPerformPromotionAnalysisForbidden creates a PerformPromotionAnalysisForbidden with default headers values
func NewPerformPromotionAnalysisForbidden() *PerformPromotionAnalysisForbidden {
	return &PerformPromotionAnalysisForbidden{}
}

/*
PerformPromotionAnalysisForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PerformPromotionAnalysisForbidden struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this perform promotion analysis forbidden response has a 2xx status code
func (o *PerformPromotionAnalysisForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this perform promotion analysis forbidden response has a 3xx status code
func (o *PerformPromotionAnalysisForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this perform promotion analysis forbidden response has a 4xx status code
func (o *PerformPromotionAnalysisForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this perform promotion analysis forbidden response has a 5xx status code
func (o *PerformPromotionAnalysisForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this perform promotion analysis forbidden response a status code equal to that given
func (o *PerformPromotionAnalysisForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *PerformPromotionAnalysisForbidden) Error() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisForbidden  %+v", 403, o.Payload)
}

func (o *PerformPromotionAnalysisForbidden) String() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisForbidden  %+v", 403, o.Payload)
}

func (o *PerformPromotionAnalysisForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PerformPromotionAnalysisForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPerformPromotionAnalysisNotFound creates a PerformPromotionAnalysisNotFound with default headers values
func NewPerformPromotionAnalysisNotFound() *PerformPromotionAnalysisNotFound {
	return &PerformPromotionAnalysisNotFound{}
}

/*
PerformPromotionAnalysisNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PerformPromotionAnalysisNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this perform promotion analysis not found response has a 2xx status code
func (o *PerformPromotionAnalysisNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this perform promotion analysis not found response has a 3xx status code
func (o *PerformPromotionAnalysisNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this perform promotion analysis not found response has a 4xx status code
func (o *PerformPromotionAnalysisNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this perform promotion analysis not found response has a 5xx status code
func (o *PerformPromotionAnalysisNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this perform promotion analysis not found response a status code equal to that given
func (o *PerformPromotionAnalysisNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *PerformPromotionAnalysisNotFound) Error() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisNotFound  %+v", 404, o.Payload)
}

func (o *PerformPromotionAnalysisNotFound) String() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisNotFound  %+v", 404, o.Payload)
}

func (o *PerformPromotionAnalysisNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PerformPromotionAnalysisNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPerformPromotionAnalysisInternalServerError creates a PerformPromotionAnalysisInternalServerError with default headers values
func NewPerformPromotionAnalysisInternalServerError() *PerformPromotionAnalysisInternalServerError {
	return &PerformPromotionAnalysisInternalServerError{}
}

/*
PerformPromotionAnalysisInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PerformPromotionAnalysisInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this perform promotion analysis internal server error response has a 2xx status code
func (o *PerformPromotionAnalysisInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this perform promotion analysis internal server error response has a 3xx status code
func (o *PerformPromotionAnalysisInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this perform promotion analysis internal server error response has a 4xx status code
func (o *PerformPromotionAnalysisInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this perform promotion analysis internal server error response has a 5xx status code
func (o *PerformPromotionAnalysisInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this perform promotion analysis internal server error response a status code equal to that given
func (o *PerformPromotionAnalysisInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *PerformPromotionAnalysisInternalServerError) Error() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisInternalServerError  %+v", 500, o.Payload)
}

func (o *PerformPromotionAnalysisInternalServerError) String() string {
	return fmt.Sprintf("[POST /executions/promotions/{id}][%d] performPromotionAnalysisInternalServerError  %+v", 500, o.Payload)
}

func (o *PerformPromotionAnalysisInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PerformPromotionAnalysisInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
