// Code generated by go-swagger; DO NOT EDIT.

package promotions_executions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bartsimp/talend-rest-go/models"
)

// NewPerformPromotionAnalysisParams creates a new PerformPromotionAnalysisParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPerformPromotionAnalysisParams() *PerformPromotionAnalysisParams {
	return &PerformPromotionAnalysisParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPerformPromotionAnalysisParamsWithTimeout creates a new PerformPromotionAnalysisParams object
// with the ability to set a timeout on a request.
func NewPerformPromotionAnalysisParamsWithTimeout(timeout time.Duration) *PerformPromotionAnalysisParams {
	return &PerformPromotionAnalysisParams{
		timeout: timeout,
	}
}

// NewPerformPromotionAnalysisParamsWithContext creates a new PerformPromotionAnalysisParams object
// with the ability to set a context for a request.
func NewPerformPromotionAnalysisParamsWithContext(ctx context.Context) *PerformPromotionAnalysisParams {
	return &PerformPromotionAnalysisParams{
		Context: ctx,
	}
}

// NewPerformPromotionAnalysisParamsWithHTTPClient creates a new PerformPromotionAnalysisParams object
// with the ability to set a custom HTTPClient for a request.
func NewPerformPromotionAnalysisParamsWithHTTPClient(client *http.Client) *PerformPromotionAnalysisParams {
	return &PerformPromotionAnalysisParams{
		HTTPClient: client,
	}
}

/*
PerformPromotionAnalysisParams contains all the parameters to send to the API endpoint

	for the perform promotion analysis operation.

	Typically these are written to a http.Request.
*/
type PerformPromotionAnalysisParams struct {

	// Body.
	Body *models.PromotionExecutionDetails

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the perform promotion analysis params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PerformPromotionAnalysisParams) WithDefaults() *PerformPromotionAnalysisParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the perform promotion analysis params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PerformPromotionAnalysisParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) WithTimeout(timeout time.Duration) *PerformPromotionAnalysisParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) WithContext(ctx context.Context) *PerformPromotionAnalysisParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) WithHTTPClient(client *http.Client) *PerformPromotionAnalysisParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) WithBody(body *models.PromotionExecutionDetails) *PerformPromotionAnalysisParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) SetBody(body *models.PromotionExecutionDetails) {
	o.Body = body
}

// WithID adds the id to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) WithID(id string) *PerformPromotionAnalysisParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the perform promotion analysis params
func (o *PerformPromotionAnalysisParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PerformPromotionAnalysisParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
