// Code generated by go-swagger; DO NOT EDIT.

package promotions_executables_authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddPromotionUserParams creates a new AddPromotionUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddPromotionUserParams() *AddPromotionUserParams {
	return &AddPromotionUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddPromotionUserParamsWithTimeout creates a new AddPromotionUserParams object
// with the ability to set a timeout on a request.
func NewAddPromotionUserParamsWithTimeout(timeout time.Duration) *AddPromotionUserParams {
	return &AddPromotionUserParams{
		timeout: timeout,
	}
}

// NewAddPromotionUserParamsWithContext creates a new AddPromotionUserParams object
// with the ability to set a context for a request.
func NewAddPromotionUserParamsWithContext(ctx context.Context) *AddPromotionUserParams {
	return &AddPromotionUserParams{
		Context: ctx,
	}
}

// NewAddPromotionUserParamsWithHTTPClient creates a new AddPromotionUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddPromotionUserParamsWithHTTPClient(client *http.Client) *AddPromotionUserParams {
	return &AddPromotionUserParams{
		HTTPClient: client,
	}
}

/*
AddPromotionUserParams contains all the parameters to send to the API endpoint

	for the add promotion user operation.

	Typically these are written to a http.Request.
*/
type AddPromotionUserParams struct {

	/* PromotionID.

	   Promotion ID
	*/
	PromotionID string

	/* UserID.

	   User ID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add promotion user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPromotionUserParams) WithDefaults() *AddPromotionUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add promotion user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddPromotionUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add promotion user params
func (o *AddPromotionUserParams) WithTimeout(timeout time.Duration) *AddPromotionUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add promotion user params
func (o *AddPromotionUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add promotion user params
func (o *AddPromotionUserParams) WithContext(ctx context.Context) *AddPromotionUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add promotion user params
func (o *AddPromotionUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add promotion user params
func (o *AddPromotionUserParams) WithHTTPClient(client *http.Client) *AddPromotionUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add promotion user params
func (o *AddPromotionUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPromotionID adds the promotionID to the add promotion user params
func (o *AddPromotionUserParams) WithPromotionID(promotionID string) *AddPromotionUserParams {
	o.SetPromotionID(promotionID)
	return o
}

// SetPromotionID adds the promotionId to the add promotion user params
func (o *AddPromotionUserParams) SetPromotionID(promotionID string) {
	o.PromotionID = promotionID
}

// WithUserID adds the userID to the add promotion user params
func (o *AddPromotionUserParams) WithUserID(userID string) *AddPromotionUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the add promotion user params
func (o *AddPromotionUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *AddPromotionUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param promotionId
	if err := r.SetPathParam("promotionId", o.PromotionID); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
