// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RunProfileRescheduleOptions run profile reschedule options
//
// swagger:model RunProfileRescheduleOptions
type RunProfileRescheduleOptions struct {

	// Run profile reschedule method
	// Enum: [DEFAULT DUPLICATE_RUN_PROFILES CLUSTER_RUN_PROFILE]
	Method string `json:"method,omitempty"`

	// Run profile to be used from cluster
	RunProfileID string `json:"runProfileId,omitempty"`
}

// Validate validates this run profile reschedule options
func (m *RunProfileRescheduleOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var runProfileRescheduleOptionsTypeMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DEFAULT","DUPLICATE_RUN_PROFILES","CLUSTER_RUN_PROFILE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		runProfileRescheduleOptionsTypeMethodPropEnum = append(runProfileRescheduleOptionsTypeMethodPropEnum, v)
	}
}

const (

	// RunProfileRescheduleOptionsMethodDEFAULT captures enum value "DEFAULT"
	RunProfileRescheduleOptionsMethodDEFAULT string = "DEFAULT"

	// RunProfileRescheduleOptionsMethodDUPLICATERUNPROFILES captures enum value "DUPLICATE_RUN_PROFILES"
	RunProfileRescheduleOptionsMethodDUPLICATERUNPROFILES string = "DUPLICATE_RUN_PROFILES"

	// RunProfileRescheduleOptionsMethodCLUSTERRUNPROFILE captures enum value "CLUSTER_RUN_PROFILE"
	RunProfileRescheduleOptionsMethodCLUSTERRUNPROFILE string = "CLUSTER_RUN_PROFILE"
)

// prop value enum
func (m *RunProfileRescheduleOptions) validateMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, runProfileRescheduleOptionsTypeMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RunProfileRescheduleOptions) validateMethod(formats strfmt.Registry) error {
	if swag.IsZero(m.Method) { // not required
		return nil
	}

	// value enum
	if err := m.validateMethodEnum("method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this run profile reschedule options based on context it is used
func (m *RunProfileRescheduleOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RunProfileRescheduleOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunProfileRescheduleOptions) UnmarshalBinary(b []byte) error {
	var res RunProfileRescheduleOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
