// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Runtime runtime
//
// swagger:model Runtime
type Runtime struct {

	// Remote engine cluster id
	// Example: 5c9a51dc7b353e43c7fc787c
	ClusterID string `json:"clusterId,omitempty"`

	// Remote engine id
	// Example: 5c9a51dc7b353e43c7fc787c
	EngineID string `json:"engineId,omitempty"`

	// Runtime id
	// Example: 5c9a51dc7b353e43c7fc787c
	ID string `json:"id,omitempty"`

	// Engine run profile ID
	// Example: 5c9a51dc7b353e43c7fc783c
	RunProfileID string `json:"runProfileId,omitempty"`

	// Type of runtime
	// Example: CLOUD
	// Enum: [CLOUD REMOTE_ENGINE REMOTE_ENGINE_CLUSTER CLOUD_EXCLUSIVE]
	Type string `json:"type,omitempty"`
}

// Validate validates this runtime
func (m *Runtime) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var runtimeTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CLOUD","REMOTE_ENGINE","REMOTE_ENGINE_CLUSTER","CLOUD_EXCLUSIVE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		runtimeTypeTypePropEnum = append(runtimeTypeTypePropEnum, v)
	}
}

const (

	// RuntimeTypeCLOUD captures enum value "CLOUD"
	RuntimeTypeCLOUD string = "CLOUD"

	// RuntimeTypeREMOTEENGINE captures enum value "REMOTE_ENGINE"
	RuntimeTypeREMOTEENGINE string = "REMOTE_ENGINE"

	// RuntimeTypeREMOTEENGINECLUSTER captures enum value "REMOTE_ENGINE_CLUSTER"
	RuntimeTypeREMOTEENGINECLUSTER string = "REMOTE_ENGINE_CLUSTER"

	// RuntimeTypeCLOUDEXCLUSIVE captures enum value "CLOUD_EXCLUSIVE"
	RuntimeTypeCLOUDEXCLUSIVE string = "CLOUD_EXCLUSIVE"
)

// prop value enum
func (m *Runtime) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, runtimeTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Runtime) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this runtime based on context it is used
func (m *Runtime) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Runtime) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Runtime) UnmarshalBinary(b []byte) error {
	var res Runtime
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
