// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StandardRunProfileResponse Pipeline run profile of type 'Standard'
//
// swagger:model StandardRunProfileResponse
type StandardRunProfileResponse struct {

	// Configuration
	// Required: true
	Configuration *Configuration `json:"configuration"`

	// Created on
	// Read Only: true
	// Format: date-time
	CreateDate strfmt.DateTime `json:"createDate,omitempty"`

	// Description
	// Example: Run profile used by default
	Description string `json:"description,omitempty"`

	// Pipeline engine id
	// Example: 5f7eff3245ecf259a1c56daa
	EngineID string `json:"engineId,omitempty"`

	// Execution framework
	// Example: Spark local
	// Required: true
	ExecutionFramework *string `json:"executionFramework"`

	// Run profile id
	// Example: 57f64991e4b0b689a64feed0
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Name
	// Example: Default run profile
	// Required: true
	Name *string `json:"name"`

	// Type
	// Read Only: true
	// Enum: [standard big-data databricks advanced]
	Type string `json:"type,omitempty"`

	// Updated on
	// Read Only: true
	// Format: date-time
	UpdateDate strfmt.DateTime `json:"updateDate,omitempty"`
}

// Validate validates this standard run profile response
func (m *StandardRunProfileResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfiguration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionFramework(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StandardRunProfileResponse) validateConfiguration(formats strfmt.Registry) error {

	if err := validate.Required("configuration", "body", m.Configuration); err != nil {
		return err
	}

	if m.Configuration != nil {
		if err := m.Configuration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configuration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("configuration")
			}
			return err
		}
	}

	return nil
}

func (m *StandardRunProfileResponse) validateCreateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.CreateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("createDate", "body", "date-time", m.CreateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *StandardRunProfileResponse) validateExecutionFramework(formats strfmt.Registry) error {

	if err := validate.Required("executionFramework", "body", m.ExecutionFramework); err != nil {
		return err
	}

	return nil
}

func (m *StandardRunProfileResponse) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var standardRunProfileResponseTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["standard","big-data","databricks","advanced"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		standardRunProfileResponseTypeTypePropEnum = append(standardRunProfileResponseTypeTypePropEnum, v)
	}
}

const (

	// StandardRunProfileResponseTypeStandard captures enum value "standard"
	StandardRunProfileResponseTypeStandard string = "standard"

	// StandardRunProfileResponseTypeBigDashData captures enum value "big-data"
	StandardRunProfileResponseTypeBigDashData string = "big-data"

	// StandardRunProfileResponseTypeDatabricks captures enum value "databricks"
	StandardRunProfileResponseTypeDatabricks string = "databricks"

	// StandardRunProfileResponseTypeAdvanced captures enum value "advanced"
	StandardRunProfileResponseTypeAdvanced string = "advanced"
)

// prop value enum
func (m *StandardRunProfileResponse) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, standardRunProfileResponseTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *StandardRunProfileResponse) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *StandardRunProfileResponse) validateUpdateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdateDate) { // not required
		return nil
	}

	if err := validate.FormatOf("updateDate", "body", "date-time", m.UpdateDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this standard run profile response based on the context it is used
func (m *StandardRunProfileResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfiguration(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreateDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdateDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StandardRunProfileResponse) contextValidateConfiguration(ctx context.Context, formats strfmt.Registry) error {

	if m.Configuration != nil {
		if err := m.Configuration.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configuration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("configuration")
			}
			return err
		}
	}

	return nil
}

func (m *StandardRunProfileResponse) contextValidateCreateDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "createDate", "body", strfmt.DateTime(m.CreateDate)); err != nil {
		return err
	}

	return nil
}

func (m *StandardRunProfileResponse) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *StandardRunProfileResponse) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(m.Type)); err != nil {
		return err
	}

	return nil
}

func (m *StandardRunProfileResponse) contextValidateUpdateDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "updateDate", "body", strfmt.DateTime(m.UpdateDate)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StandardRunProfileResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StandardRunProfileResponse) UnmarshalBinary(b []byte) error {
	var res StandardRunProfileResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
