// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpgradeInfo upgrade info
//
// swagger:model UpgradeInfo
type UpgradeInfo struct {

	// auto upgrade failed
	AutoUpgradeFailed bool `json:"autoUpgradeFailed,omitempty"`

	// upgradable
	Upgradable bool `json:"upgradable,omitempty"`
}

// Validate validates this upgrade info
func (m *UpgradeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upgrade info based on context it is used
func (m *UpgradeInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpgradeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpgradeInfo) UnmarshalBinary(b []byte) error {
	var res UpgradeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
